name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
    test-cpp-mac:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4
            - uses: krdlab/setup-haxe@master
              with:
                haxe-version: 4.3.6

            - name: Install dependencies
              run: |
                haxelib install lime --quiet
                haxelib install openfl --quiet
                haxelib install flixel --quiet
                haxelib install flixel-ui --quiet
                curl --output ../hxcpp.zip --location https://github.com/HaxeFoundation/hxcpp/releases/download/v4.3.73/hxcpp-4.3.73.zip
                haxelib install ../hxcpp.zip --quiet

            - name: Build sample
              run: |
                cd samples/basic
                haxelib run lime build macos
                cd ../..

    test-cpp-windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
            - uses: krdlab/setup-haxe@v1
              with:
                haxe-version: 4.3.6

            - name: Install dependencies
              run: |
                haxelib install lime --quiet
                haxelib install openfl --quiet
                haxelib install flixel --quiet
                haxelib install flixel-ui --quiet
                curl --output ../hxcpp.zip --location https://github.com/HaxeFoundation/hxcpp/releases/download/v4.3.73/hxcpp-4.3.73.zip
                haxelib install ../hxcpp.zip --quiet

            - name: Build sample
              run: |
                cd samples/basic
                haxelib run lime build windows
                cd ../..

    test-cpp-linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: krdlab/setup-haxe@v1
              with:
                haxe-version: 4.3.6

            - name: Install dependencies
              run: |
                haxelib install lime --quiet
                haxelib install openfl --quiet
                haxelib install flixel --quiet
                haxelib install flixel-ui --quiet
                curl --output ../hxcpp.zip --location https://github.com/HaxeFoundation/hxcpp/releases/download/v4.3.73/hxcpp-4.3.73.zip
                haxelib install ../hxcpp.zip --quiet

            - name: Build sample
              run: |
                cd samples/basic
                haxelib run lime build linux
                cd ../..

    test-hl:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: krdlab/setup-haxe@v1
              with:
                haxe-version: 4.3.6

            - name: Install dependencies
              run: |
                haxelib install lime --quiet
                haxelib install openfl --quiet
                haxelib install flixel --quiet
                haxelib install flixel-ui --quiet

            - name: Build sample
              run: |
                cd samples/basic
                haxelib run lime build hl
                cd ../..

    test-html5:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: krdlab/setup-haxe@v1
              with:
                haxe-version: 4.3.6

            - name: Install dependencies
              run: |
                haxelib install lime --quiet
                haxelib install openfl --quiet
                haxelib install flixel --quiet
                haxelib install flixel-ui --quiet

            - name: Build sample
              run: |
                cd samples/basic
                haxelib run lime build html5
                cd ../..

    test-flash:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: krdlab/setup-haxe@v1
              with:
                haxe-version: 4.3.6

            - name: Install dependencies
              run: |
                haxelib install lime --quiet
                haxelib install openfl --quiet
                haxelib install flixel --quiet
                haxelib install flixel-ui --quiet

            - name: Build sample
              run: |
                cd samples/basic
                haxelib run lime build flash
                cd ../..
                
