name: Deploy Playground sample to Github Pages

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - uses: krdlab/setup-haxe@v1
              with:
                haxe-version: 4.3.6

            - name: Install dependencies
              run: |
                haxelib install lime --quiet
                haxelib install openfl --quiet
                haxelib install flixel --quiet
                haxelib install flixel-ui --quiet
                curl --output ../hxcpp.zip --location https://github.com/HaxeFoundation/hxcpp/releases/download/v4.3.73/hxcpp-4.3.73.zip
                haxelib install ../hxcpp.zip --quiet

            - name: Build playground sample
              run: |
                cd samples/playground
                haxelib run lime build html5
                cd ../..

            - name: Deploy playground sample
              uses: peaceiris/actions-gh-pages@v4
              if: github.ref == 'refs/heads/dev'
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./samples/playground/export/html5/bin
